### ISSUE TITLE
unable to sell drugs

### ISSUE THREAD

**Issue by uknowwhoiam2301** [Senlar/ncrp_issues#101]
u can press h to sell drugs but no transaction actually happens

when u have pre scaled baggies normally if u hit h u can sell drugs. when u hit H at the moment even if your offer isnt rejected no transaction actually happens 
i would expect that u would sell some drugs and earn cash

https://medal.tv/games/gta-v/clips/gA08MHJUBY0BE/d13371e8g4AW?invite=cr-MSxZN1UsNTgzOTM2ODgs

**Comment by OfficialMasuUK** [comment]
Opening different method of tracking.
