### ISSUE TITLE
Taco Libre / Public Job Payment Re-Work

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#108]
**Is your enhancement request related to a problem? Please describe.**
Re-work the public job payment system. Requested through NCRP Feedback site. Suggestions included Taco Libre paying too much plus tips. People dumping $15K tips for a $100 order.

**Describe the enhancement you'd like**
Manage flow of money with a new system for public job enhancement.

**Describe alternatives you've considered**

**Additional context**
Ref: TACO LIBRE PAYMENTS - Feedback Site
Original post by Diezel and other comments/suggestions by community members.

**Comment by Senlar** [comment]
Done
