### ISSUE TITLE
Add Garage for Firefly Motel

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#109]
**Is your enhancement request related to a problem? Please describe.**
Add garage for this motel.

**Describe the enhancement you'd like**
Add garage please.

**Describe alternatives you've considered**

**Additional context**
by Wavy
Ref: Add Garage for Firefly Motel - Feedback site

**Comment by OfficialMasuUK** [comment]
Already added. See https://github.com/Senlar/ncrp_issues/issues/107.
