### ISSUE TITLE
getting stuck in my house

### ISSUE THREAD

**Issue by uknowwhoiam2301** [Senlar/ncrp_issues#114]
<h2>What bug have you found?</h2>
i can enter my house but when i go to leave i cant and my third eye gets stuck along with it opening a weapon wheel

<h2>What do you expect should happen?</h2>
i should be able to use my third eye to exit my house

<h2>Anything to support your bug report?</h2>

https://cdn.discordapp.com/attachments/959255075371491418/963680895712264202/628187C2-994C-483E-BBFA-0A02FF2B60CE.jpg

https://cdn.discordapp.com/attachments/959255075371491418/963678596948455535/983F0C96-7B31-4C5A-9B2C-72A09578FCED.jpg

**Comment by Senlar** [comment]
Fixed
