### ISSUE TITLE
Hunting Shop AI Missing

### ISSUE THREAD

**Issue by VikingLothar** [Senlar/ncrp_issues#116]
<h2>What bug have you found?</h2>
Hunting Shop Vendor and Game Warden missing. Unable to sell meats or apply for hunting license.

<h2>What do you expect should happen?</h2>

AI to be in their respective spots and work properly.

<h2>Anything to support your bug report?</h2>

![Bug](https://user-images.githubusercontent.com/103540694/163509012-85794e5b-684e-44c1-bf20-a060a5f242ec.png)
![Bug2](https://user-images.githubusercontent.com/103540694/163509084-3eb229fc-8b91-41cc-bea5-63a130f3872a.png)

**Comment by Senlar** [comment]
Fixed at next restart!
