### ISSUE TITLE
Froze in buying menu when entering a quantity / Map size issue

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#12]
<h2>What bug have you found?</h2>
When buying an item and entering the quantity, it freezes the game. Also, when you have a GPS it shows the map really big and can't be changed in settings. Will go to normal once you get in a vehicle and work okay the rest of your play-session.

<h2>What do you expect should happen?</h2>

No freezing and the map shouldn't be so big.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/76237152/159980129-51b1f6bf-f3a1-4d3d-a4bd-02f12e2e4539.png)
![image](https://user-images.githubusercontent.com/76237152/159980173-7d4961ce-2796-4af4-af36-4ae38d065d44.png)

@hellocrash

**Comment by Senlar** [comment]
Fixed a while back
