### ISSUE TITLE
cant eat, get into pockets, or drive cars

### ISSUE THREAD

**Issue by uknowwhoiam2301** [Senlar/ncrp_issues#120]
<h2>What bug have you found?</h2>
i am unable to get into my inventory
 Describe in good detail what bug you have found as well as list the steps to reproduce if known*
when you go to eat food it makes u unable to eat food, get into cars, use your radio etc
<h2>What do you expect should happen?</h2>
u should be able to do/ use whats listed above

<h2>Anything to support your bug report?</h2>
https://medal.tv/games/gta-v/clips/jNpbLunDOsVyj/d1337yg6pnIW?invite=cr-MSxKeTYsNTgzOTM2ODgs
in this clip im trying to eat food and use my radio

**Comment by Senlar** [comment]
Fixed
