### ISSUE TITLE
CF Vehicle List Has Outdated Cars?

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#134]
<h2>What bug have you found?</h2>

frank asked for a raptor but i drove there and nothing was there. I think the car didn’t pop up because it was a ford raptor, which is no longer in the city, Cause he wanted to me to bring back a raptor

<h2>What do you expect should happen?</h2>

<h2>Anything to support your bug report?</h2>

No F8 or video - submitted by kc1337

**Comment by OfficialMasuUK** [comment]
Looked into the issue. It wasn't trying to pull the 2019 Ford Raptor, it was trying to get the GTA Raptor (Three wheeled buggy type vehicle). However, that seemingly had the wrong hash. Updated hash. Should be good now.
