### ISSUE TITLE
Vehicle Damage Is Wonky

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#135]
<h2>What bug have you found?</h2>
Having some issues with repairing vehicles and them just crumpling up like nati-lite beer cans. (tunkwa)
 There are several vehicles that have been doing this including the D8 cars. But others are fine and can get / stay repaired. (Raven)
 Last night the Karuma looked like a lambo. (Tunkwa)
 Body was fine just engine was fucked
Same effect happened in dev yesterday with xontiac except while driving the car just set itself on fire. (Honton)

<h2>What do you expect should happen?</h2>

Vehicle damage should be a little more accurate/not crumble when people get in/out.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/76237152/171859199-fe4047fc-d3f7-48fd-a3f8-cd6e0ca4c595.png)

Two tickets merged here - One from Honton, One from Tunk.

**Comment by Senlar** [comment]
@OfficialMasuUK Here it is.

**Comment by OfficialMasuUK** [comment]
Fix put in yesterday.
