### ISSUE TITLE
Soba Noodles Lower Regen Than Other Food

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#136]
<h2>What bug have you found?</h2>
Soba Noodles don't give the same amount of Energy as Pizza from Pizza This. The noodles are actually the worst 4 star food currently.

<h2>What do you expect should happen?</h2>

Replenish the same as other similar 4 star food items

<h2>Anything to support your bug report?</h2>

No - Submitted by Big O

**Comment by OfficialMasuUK** [comment]
Looked into and brought up to the same standard as all other 4 star foods.
