### ISSUE TITLE
Visible Bounding Box - MRPD

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#16]
<h2>What bug have you found?</h2>

Visible red lines at MRPD from a bounding box.
<h2>What do you expect should happen?</h2>

shouldn't see them

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/76237152/159983000-9499ea91-5046-4a00-9bf7-cdc7976e8916.png)
![image](https://user-images.githubusercontent.com/76237152/159983036-e92aefe3-638a-4507-aff1-c0d44c16952b.png)
![image](https://user-images.githubusercontent.com/76237152/159983057-9f24f356-f679-4e4c-aca6-86dec1b6594a.png)
@novoa @ambrosia

**Comment by Senlar** [comment]
Fixed
