### ISSUE TITLE
Place Time Limit on Reinstating Drivers License

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#29]
<h2>Feature you are requesting</h2>

Determine a timeframe that prevents players from losing their DL and just buying it as soon as they get back to the license bureau.

<h2>What are the benefits to your feature?</h2>

There should be significant consequences to losing your license, and that should be a short period of time where you can't just go buy the license in 5 minutes. Could also build an escalating punishment into this, where first revocation is X, second ix X x 50%, third is X x 100% etc etc

<h2>Anything to support your feature request?</h2>

Crims don't care if they have to buy a license because it's cheap and they can do it ASAP.

@fallenacolyte and anyone who is/was a cop.

**Comment by Senlar** [comment]
Done via new license system, this is an RP matter now and players will have to go through a Bullhead Lawyer to get a license back.
