### ISSUE TITLE
WN/COSA Cafeteria

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#38]
<h2>What bug have you found?</h2>

WN and COSA don't have a cafeteria (_Amir may have fixed this recently, but I'm old and I forget_) @amirradman  ?

<h2>What do you expect should happen?</h2>

Employees gotta eat.

<h2>Anything to support your bug report?</h2>

**Comment by amirradman** [comment]
This has already been fixed and is in live.
