### ISSUE TITLE
Garbage Panties and Good Panties Need Distinguishable Images

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#41]
<h2>What bug have you found?</h2>

Garbage panties and the sellable panties have the same image.

<h2>What do you expect should happen?</h2>

Should be different

<h2>Anything to support your bug report?</h2>

@pawzey
Trash item showing as panties and looks the same as panties which confuses people. Fix this in modules/items/server.lua

**Comment by Senlar** [comment]
This has been completed
