### ISSUE TITLE
MEDKIT Shows Wrong Message

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#47]
<h2>What bug have you found?</h2>

When you use a medkit, you get a message that you need something stronger.

<h2>What do you expect should happen?</h2>

Shouldn't display that message.

<h2>Anything to support your bug report?</h2>

@pawzey
![image](https://user-images.githubusercontent.com/76237152/159992545-933e91a0-c6b1-4d4c-95cc-30052853c63b.png)

**Comment by Senlar** [comment]
This was fixed a while back, was left on list.
