### ISSUE TITLE
Dropping Player Note Deleted Grage

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#52]
<h2>What bug have you found?</h2>

Bumpy drops a note near a player garage. Don tries to pick it up and the garage is deleted ONLY for Don. Bumpy can still see the garage.

<h2>What do you expect should happen?</h2>

Notes should have nothing against a garage like that. 
<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/76237152/159993492-13fb7115-1c3a-4d3f-8b4b-a4c8550bfc0f.png)
@pawzey

**Comment by Senlar** [comment]
Unrelated, issue is with housing and housing is being replaced.
