### ISSUE TITLE
Police MDW Only Admin Can Fine

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#56]
<h2>What bug have you found?</h2>

Only Admin in MDW can fine people. Likely fixed, but not marked off as complete.

<h2>What do you expect should happen?</h2>

Any rank (maybe even cadet) should be able to assign fines to people.

<h2>Anything to support your bug report?</h2>

No report, through conversation.

**Comment by Senlar** [comment]
This has since been corrected.
