### ISSUE TITLE
Multiple Purchase Messages Populating

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#64]
<h2>What bug have you found?</h2>

When looking at the product list from a private merchant, player was spammed with multiple messages on screen. Player didn't try to buy or sell, but message said **_"Merchant has too much of this to buy more"_**

<h2>What do you expect should happen?</h2>

No messages unless buying or selling, and should only populate one per click/enter.

<h2>Anything to support your bug report?</h2>

@pawzey
This was within an MLO that has been removed.

**Comment by Senlar** [comment]
This has sense been fixed, just wasn't cleaned off the old list.
