### ISSUE TITLE
Mt. Zonah Wardrobe/Outfit Save Location Needs Swapping.

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#7]
<h2>What bug have you found?</h2>

Wardrobe ➡️  Basement
Outfit save/use ➡️  Locker Room
Since the wardrobe was moved to the break room things have got a bit messy, you can't access the old menu for changing into your official uniform because they're overlapping (it seems to work sometimes, but it's messy nonetheless). I have also been told that the hotspot to save/access your saved outfits is still down in the basement, which was the main functionality we wanted in the break room in the first place.

Easier clothing swap/saving without menus overlapping each other.

@femme

**Comment by OfficialMasuUK** [comment]
Resolved in another issue
