### ISSUE TITLE
Go Kart Track - Vehicles Spawning On Track / Driving Through Walls

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#73]
<h2>What bug have you found?</h2>

Cars were spawning on the tracks and could drive through walls.

<h2>What do you expect should happen?</h2>

It's not supposed to do that.

<h2>Anything to support your bug report?</h2>

I'm quite certain we yeeted go karts, but for future reference this was an issue.
@rosschungus

**Comment by Senlar** [comment]
Removed track, added a different one w/o this issue.
