### ISSUE TITLE
Seat Belt Bug

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#77]
<h2>What bug have you found?</h2>

if you park a car in a garage while your seat belt is on, then the next car you get in, it appears your seat belt is on, when infact it is not. The symbol is not there however to put it on, you need to press the seat belt button twice to 'take it off' and then it shows the seat belt off icon, then you press the button again to put it on properly

<h2>What do you expect should happen?</h2>

perhaps the actions of storing a vehicle could automatically remove seatbelt, or prompt you to remove your seat belt first, would also stop people just yeeting their cars into the invisible garage at 50 odd mph

<h2>Anything to support your bug report?</h2>
@pawzeyncn

**Comment by amirradman** [comment]
@Senlar What folder is this under?

**Comment by amirradman** [comment]
Future reference: joehud
Issue is fixed
