### ISSUE TITLE
Unable to retrieve plane from pegasus garage

### ISSUE THREAD

**Issue by amirradman** [Senlar/ncrp_issues#81]
<h2>What bug have you found?</h2>

When I open pegaus garage, two duplicate planes(nimbus) show up and if I try to I click on either "Take out", two planes spawn over eachother and they both blow up

<h2>What do you expect should happen?</h2>

Only 1 plane should show in garage and allow to successfully retrieve it
<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/15365155/160228037-51ada12e-6dd4-452f-a221-a9dde0f6b843.png)

**Comment by BradNCN** [comment]
There is also a recent report regarding boats that is quite similar.

**Comment by amirradman** [comment]
Will be resolved after next server restart
