### ISSUE TITLE
MRPD Meeting Room / Armory Bounding Box

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#82]
<h2>What bug have you found?</h2>

On Dev, you can access the armory from across the hall. Unsure if happens on live.

<h2>What do you expect should happen?</h2>

should be restricted to within the armory room/walls

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/76237152/160403289-b34cc595-f3ea-451d-a552-9382325fd270.png)

**Comment by OfficialMasuUK** [comment]
Just RP. It'll be okay.
