### ISSUE TITLE
Pulling Out Boat Spawns Two

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#86]
<h2>What bug have you found?</h2>

When pulling out their boat, two boats spawn and they flip upside down. No F8 errors.

<h2>What do you expect should happen?</h2>

Boats should spawn right-side-up.

<h2>Anything to support your bug report?</h2>

Submitted by cowboy/hoss
https://medal.tv/games/gta-v/clips/fntrUe4ZJwrcf/uhS489dWPIte?invite=cr-MSxOajYsMTYxNzM0NzQs

**Comment by OfficialMasuUK** [comment]
Fixed by Sen.
