### ISSUE TITLE
 LSMS uniforms need to be replaced with new file

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#9]
<h2>What bug have you found?</h2>
Busted uniforms - attachment should fix

<h2>What do you expect should happen?</h2>

better looking medics = happy patients.

<h2>Anything to support your bug report?</h2>

[LSMSUNIFORMS_new-3.23.22.txt](https://github.com/Senlar/ncrp_issues/files/8344113/LSMSUNIFORMS_new-3.23.22.txt)

**Comment by OfficialMasuUK** [comment]
Updated
