### ISSUE TITLE
Fixing LSMS Uniforms

### ISSUE THREAD

**Issue by iamrayuu** [Senlar/ncrp_issues#93]
**Is your enhancement request related to a problem? Please describe.**
Enhancement is in regards to the broken issues around the LSMS uniform. The below is a TXT that shares the adjustments they would like to move forward with.

**Describe the enhancement you'd like**
New revamped uniforms that fix the current iffyness in the current LSMS Uniforms.

**Describe alternatives you've considered**
N/A

**Additional context**

Transcript from Discord, issue 1 of the 3 mentioned in this ticket:
https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/826233751800643595/958110560178823218/transcript-dev-c-744.htm
[LSMSUNIFORMS_new-3.23.22.txt](https://github.com/Senlar/ncrp_issues/files/8366330/LSMSUNIFORMS_new-3.23.22.txt)
l

**Comment by OfficialMasuUK** [comment]
Uniforms updated
