### ISSUE TITLE
Mt. Zonah Wardrobe and Outfit Save/Use Need Swapping

### ISSUE THREAD

**Issue by iamrayuu** [Senlar/ncrp_issues#95]
**Is your enhancement request related to a problem? Please describe.**

Quote from Transcript:
_Since the wardrobe was moved to the break room things have got a bit messy, you can't access the old menu for changing into your official uniform because they're overlapping (it seems to work sometimes, but it's messy nonetheless). I have also been told that the hotspot to save/access your saved outfits is still down in the basement, which was the main functionality we wanted in the break room in the first place._

**Describe the enhancement you'd like**
Swap the areas in which you access your wardrobe and the outfits to increase QOL for the medics at LSMS.

**Describe alternatives you've considered**
N/A

**Additional context**

Transcript from Discord, issue 3 of 3 mentioned in the ticket: 
https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/826233751800643595/958110560178823218/transcript-dev-c-744.html

**Comment by OfficialMasuUK** [comment]
Locations switched - Ready to push to live.
