### ISSUE TITLE
Old clock-in spot still at MRPD

### ISSUE THREAD

**Issue by iamrayuu** [Senlar/ncrp_issues#97]
**Is your enhancement request related to a problem? Please describe.**
The particular issue isn't pressing, but there are two different distinctly different clock-in spots in MRPD. The old one that's still out in the desk area and the one that is at the notebook at the front desk.

**Describe the enhancement you'd like**
Simply to only have one clock-in spot at MRPD, being the front desk one as it reflects the new way of clocking in.

**Describe alternatives you've considered**
N/A

**Additional context**
Issue was brought up in a dev ticket and I am simply regurgitating the information into a Github post. I don't think this is terribly pressing, but I think for the sake of clarity and consistency in our new updates that this should happen eventually and is an easy change?

**Comment by OfficialMasuUK** [comment]
Fixed.
