### ISSUE TITLE
Police/LSMS Given notifications for homicide when animals killed.

### ISSUE THREAD

**Issue by BradNCN** [Senlar/ncrp_issues#99]
<h2>What bug have you found?</h2>

Kill and animal and apparently LSMS/LSPD/SASP are getting notifications for all them as homicides.

<h2>What do you expect should happen?</h2>

Shouldn't get any notification when an animal is killed. This could be improved in the future so BCSO/Park Rangers receive some type of notification for this so they can ensure licenses/tags/hunting areas are within the state laws for hunting and gaming.

<h2>Anything to support your bug report?</h2>

No - Was mentioned to me by LSMS and Police

**Comment by OfficialMasuUK** [comment]
Issue fixed.
